// This file is autogenerated. Changes will be overwritten.
#include "EWIEGA46WW/moc_animal.cpp"
#include "EWIEGA46WW/moc_cat.cpp"
#include "EWIEGA46WW/moc_dog.cpp"
#include "EWIEGA46WW/moc_mammal.cpp"
